# Generated by Django 4.2.3 on 2023-07-16 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='current_weather',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notification_period',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='main.subscription'),
        ),
    ]
